msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
tex_softLight="soft3.png"
tex_normalMakeup="02_make.png"
