warp_mesh = "Beauty06.bsm2"
draw_order = ['TriMat', 'retouch', 'Refl', 'Rough', 'fire']

#TriMat
[materials.TriMat]
vs = "fstri.vert"
fs = "lut.frag"
blend = "off"
backfaces = true
shadow = false
zwrite = false
[materials.TriMat.samplers]
luttex="bwc.png"

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="redmask_new_3.png"
lookupTexTeeth="teeth_highlighter5.png"
lookupTexEyes="lut_80_percent.png"
tex_normalMakeup="makeup.png"
tex_softLight="soft_princess.png"
tex_highlight="40.png"
luttex="bwc.png"

# PBR
[materials.Refl]
vs = "refl.vert"
fs = "refl.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Refl.samplers]
tex_diffuse="gold_BaseColor.png"
tex_normal="gold_Normal.png"
tex_metallic="gold_Metallic.png"
tex_roughness="gold_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Rough]
vs = "rough.vert"
fs = "rough.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Rough.samplers]
tex_diffuse="black_BaseColor.png"
tex_normal="no_Normal.png"
tex_metallic="black_Metallic.png"
tex_roughness="black_Roughness.png"

# PBR
[materials.fire]
vs = "fire.vert"
fs = "video_a.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = false
shadow = false
samplers = {}
